root         = "."
testdata_dir = "testdata"
tmp_dir      = "tmp"

[build]
args_bin = [
  "-debug",
  "-log.add.source=true",
  "-opentelemetry.trace.exporter=otlp-http",
  "-opentelemetry.metric.exporter=otlp-http",
  "-authn.access.token.duration=24h",
  "-authn.refresh.token.duration=720h",
  "-authn.private.key.file=./certs/jwt.key",
  "-authn.public.key.file=./certs/jwt.pub",
  "-authn.symmetric.key.file=./certs/aes-256-symmetric-hex.key",
  "-http.server.pprof.enabled=false",
  "-http.server.cors.enabled=true",
  "-http.server.cors.allowed.origins=http://localhost:8080,http://localhost:5173",
  "-http.server.ip.rate.limiter.enabled=true",
  "-http.server.ip.rate.limiter.burst=400",
  "-http.server.ip.rate.limiter.limit=100.0",
  "-http.server.port=8080",
]
bin = "./build/go-rest-api-service-template"
cmd = "make build"
delay = 200
exclude_dir = [
  "node_modules",
  "frontend",
  "assets",
  "tmp",
  "vendor",
  "testdata",
  "docs",
  "build",
  "mocks",
  "dev-env",
  "test",
]
exclude_file = [
  "docs/docs.go",
]
exclude_regex = [
  "_test.go",
  ".tmpl",
]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = [
]
include_ext = [
  "go",
  "tpl",
  "tmpl",
  "html",
]
include_file = [
]
kill_delay = "5s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = [
]
pre_cmd = [
]
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = true

[color]
app     = ""
build   = "yellow"
main    = "magenta"
runner  = "green"
watcher = "cyan"

[log]
main_only = false
time      = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll      = true
