# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.0.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
# References:
# https://developers.redhat.com/blog/2019/01/15/podman-managing-containers-pods#
# https://www.redhat.com/sysadmin/podman-play-kube-updates
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-04T14:57:16Z"
  labels:
    app: dev-service-pod
  name: dev-service-pod
spec:
  containers:
    - name: postgres
      args:
        - postgres
      env:
        - name: TZ
          value: UTC
        - name: PGTZ
          value: UTC
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: username
        - name: POSTGRES_DB
          value: go-template-service
      image: docker.io/library/postgres:16
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - name: go-service-template-db-volume-host
          mountPath: /var/lib/postgresq/data

  volumes:
    - name: go-service-template-db-volume-host
      hostPath:
        path: /tmp/go-service-template-db-volume-host
        type: Directory
