global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

storage:
  tsdb:
    # A 10min time window is enough because it can easily absorb retries and network delays.
    out_of_order_time_window: 10m
# tracing:
#   endpoint: "localhost:4317"
#   insecure: true
#   compression: "gzip"
#   timeout: "10s"

otlp:
  keep_identifying_resource_attributes: true
  translation_strategy: NoUTF8EscapingWithSuffixes
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
