definitions:
  model.Check:
    description: Health check of the service
    properties:
      data:
        additionalProperties: true
        format: map
        type: object
      kind:
        example: database
        format: string
        type: string
      name:
        example: database
        format: string
        type: string
      status:
        example: true
        format: boolean
        type: boolean
    type: object
  model.CreateUserRequest:
    description: CreateUserRequest represents the input for the CreateUser method
    properties:
      email:
        example: my@email.com
        format: email
        type: string
      first_name:
        example: John
        format: string
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      last_name:
        example: Doe
        format: string
        type: string
      password:
        example: ThisIs4Passw0rd
        format: string
        type: string
    type: object
  model.HTTPMessage:
    description: HTTPMessage represents a message to be sent to the client though
      the HTTP REST API.
    properties:
      message:
        example: Hello, World!
        format: string
        type: string
      method:
        example: GET
        format: string
        type: string
      path:
        example: /api/v1/hello
        format: string
        type: string
      status_code:
        example: 200
        format: int32
        type: integer
      timestamp:
        example: "2021-01-01T00:00:00Z"
        format: date-time
        type: string
    type: object
  model.Health:
    description: Health check of the service
    properties:
      checks:
        items:
          $ref: '#/definitions/model.Check'
          format: array
        type: array
      status:
        example: true
        format: boolean
        type: boolean
    type: object
  model.ListUsersResponse:
    description: ListUsersResponse represents a list of users
    properties:
      items:
        items:
          $ref: '#/definitions/model.User'
        type: array
      paginator:
        $ref: '#/definitions/model.Paginator'
    type: object
  model.Paginator:
    description: Paginator represents a paginator.
    properties:
      limit:
        example: 10
        format: int
        type: integer
      next_page:
        example: http://localhost:8080/users?next_token=ZmZmZmZmZmYtZmZmZi0tZmZmZmZmZmY=&limit=10
        format: string
        type: string
      next_token:
        example: ZmZmZmZmZmYtZmZmZi0tZmZmZmZmZmY=
        format: string
        type: string
      prev_page:
        example: http://localhost:8080/users?prev_token=ZmZmZmZmZmYtZmZmZi0tZmZmZmZmZmY=&limit=10
        format: string
        type: string
      prev_token:
        example: ZmZmZmZmZmYtZmZmZi0tZmZmZmZmZmY=
        format: string
        type: string
      size:
        example: 10
        format: int
        type: integer
    type: object
  model.UpdateUserRequest:
    description: UpdateUserRequest represents the input for the UpdateUser method
    properties:
      disabled:
        example: false
        format: boolean
        type: boolean
      email:
        example: my@email.com
        format: email
        type: string
      first_name:
        example: John
        format: string
        type: string
      last_name:
        example: Doe
        format: string
        type: string
      password:
        example: ThisIs4Passw0rd
        format: string
        type: string
    type: object
  model.User:
    description: User represents a user entity
    properties:
      created_at:
        example: "2021-01-01T00:00:00Z"
        format: date-time
        type: string
      disabled:
        example: false
        format: boolean
        type: boolean
      email:
        example: my@email.com
        format: email
        type: string
      first_name:
        example: John
        format: string
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      last_name:
        example: Doe
        format: string
        type: string
      updated_at:
        example: "2021-01-01T00:00:00Z"
        format: date-time
        type: string
    type: object
  model.Version:
    description: Version is the struct that holds the version information.
    properties:
      build_date:
        example: "2021-01-01T00:00:00Z"
        format: string
        type: string
      git_branch:
        example: main
        format: string
        type: string
      git_commit:
        example: abcdef123456
        format: string
        type: string
      go_version:
        example: go1.24.1
        format: string
        type: string
      go_version_arch:
        example: amd64
        format: string
        type: string
      go_version_os:
        example: linux
        format: string
        type: string
      version:
        example: 1.0.0
        format: string
        type: string
    type: object
info:
  contact:
    email: info@qu3ry.me
    name: API Support
    url: https://qu3ry.me
  description: |-
    This is a service template for building RESTful APIs in Go.
    It uses a PostgreSQL database to store user information.
    The service provides:
    - CRUD operations for users.
    - Health and version endpoints.
    - Configuration using environment variables or command line arguments.
    - Debug mode to enable debug logging.
    - TLS enabled to secure the communication.
  title: Go REST API Service Template
  version: v1
paths:
  /health/status:
    get:
      description: Check health status of the service pinging the database and go
        metrics
      operationId: 0986a6ff-aa83-4b06-9a16-7e338eaa50d1
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Health'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPMessage'
      summary: Check health status
      tags:
      - Health
  /users:
    get:
      description: List users with pagination and filtering
      operationId: b51b8ab6-4bb4-4b37-af5c-9825ba7e71e5
      parameters:
      - description: 'Comma-separated list of fields to sort by. Example: first_name
          ASC, created_at DESC'
        format: string
        in: query
        name: sort
        type: string
      - description: 'Filter field. Example: id=1 AND first_name=''John'''
        format: string
        in: query
        name: filter
        type: string
      - description: 'Fields to return. Example: id,first_name,last_name'
        format: string
        in: query
        name: fields
        type: string
      - description: Next cursor
        format: string
        in: query
        name: next_token
        type: string
      - description: Previous cursor
        format: string
        in: query
        name: prev_token
        type: string
      - description: Limit
        format: int
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ListUsersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPMessage'
      summary: List users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: |-
        Create new user from scratch.
        If the id is not provided, it will be generated automatically.
      operationId: 8a1488b0-2d2c-42a0-a57a-6560aaf3ec76
      parameters:
      - description: Create user request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPMessage'
      summary: Create user
      tags:
      - Users
  /users/{user_id}:
    delete:
      description: Delete a user
      operationId: 48e60e0a-ea1c-46d4-8729-c47dd82a4e93
      parameters:
      - description: The user ID in UUID format
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPMessage'
      summary: Delete a user
      tags:
      - Users
    get:
      description: Get a user by ID
      operationId: b823ba3c-3b83-4eaa-bdf7-ce1b05237f23
      parameters:
      - description: The user ID in UUID format
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPMessage'
      summary: Get a user by ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update a user
      operationId: a7979074-e16c-4aec-86e0-e5a154bbfc51
      parameters:
      - description: The user ID in UUID format
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      - description: User update request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.HTTPMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPMessage'
      summary: Update a user
      tags:
      - Users
  /version:
    get:
      description: Get the version of the service
      operationId: d85b4a3f-b032-4dd1-b3ab-bc9a00f95eb5
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Version'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPMessage'
      summary: Get the version of the service
      tags:
      - Version
swagger: "2.0"
