definitions:
  handler.Check:
    description: Health check of the service
    properties:
      data:
        additionalProperties: true
        format: map
        type: object
      kind:
        example: database
        format: string
        type: string
      name:
        example: database
        format: string
        type: string
      status:
        example: "true"
        format: boolean
        type: string
    type: object
  handler.CreateUserRequest:
    description: CreateUserRequest represents the input for the CreateUser method
    properties:
      email:
        example: my@email.com
        format: email
        type: string
      first_name:
        example: John
        format: string
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      last_name:
        example: Doe
        format: string
        type: string
      password:
        example: ThisIs4Passw0rd
        format: string
        type: string
    type: object
  handler.Health:
    description: Health check of the service
    properties:
      checks:
        items:
          $ref: '#/definitions/handler.Check'
          format: array
        type: array
      status:
        example: "true"
        format: boolean
        type: string
    type: object
  handler.ListUsersResponse:
    description: ListUsersResponse represents a list of users
    properties:
      items:
        items:
          $ref: '#/definitions/handler.User'
        type: array
      paginator:
        $ref: '#/definitions/paginator.Paginator'
    type: object
  handler.UpdateUserRequest:
    description: UpdateUserRequest represents the input for the UpdateUser method
    properties:
      disabled:
        example: false
        format: boolean
        type: boolean
      email:
        example: my@email.com
        format: email
        type: string
      first_name:
        example: John
        format: string
        type: string
      last_name:
        example: Doe
        format: string
        type: string
      password:
        example: ThisIs4Passw0rd
        format: string
        type: string
    type: object
  handler.User:
    description: User represents a user entity
    properties:
      created_at:
        example: "2021-01-01T00:00:00Z"
        format: date-time
        type: string
      disabled:
        example: false
        format: boolean
        type: boolean
      email:
        example: my@email.com
        format: email
        type: string
      first_name:
        example: John
        format: string
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      last_name:
        example: Doe
        format: string
        type: string
      updated_at:
        example: "2021-01-01T00:00:00Z"
        format: date-time
        type: string
    type: object
  handler.Version:
    properties:
      build_date:
        type: string
      git_branch:
        type: string
      git_commit:
        type: string
      go_version:
        type: string
      go_version_arch:
        type: string
      go_version_os:
        type: string
      version:
        type: string
    type: object
  paginator.Paginator:
    description: Paginator represents a paginator
    properties:
      limit:
        example: 10
        format: int
        type: integer
      next_page:
        example: http://localhost:8080/users?next_token=ZmZmZmZmZmYtZmZmZi0tZmZmZmZmZmY=&limit=10
        format: string
        type: string
      next_token:
        example: ZmZmZmZmZmYtZmZmZi0tZmZmZmZmZmY=
        format: string
        type: string
      prev_page:
        example: http://localhost:8080/users?prev_token=ZmZmZmZmZmYtZmZmZi0tZmZmZmZmZmY=&limit=10
        format: string
        type: string
      prev_token:
        example: ZmZmZmZmZmYtZmZmZi0tZmZmZmZmZmY=
        format: string
        type: string
      size:
        example: 10
        format: int
        type: integer
    type: object
  respond.HTTPMessage:
    properties:
      message:
        type: string
      method:
        type: string
      path:
        type: string
      status_code:
        type: integer
      timestamp:
        type: string
    type: object
info:
  contact: {}
  description: |-
    This is a service template for building RESTful APIs in Go.
    It uses a PostgreSQL database to store user information.
    The service provides:
    - CRUD operations for users.
    - Health and version endpoints.
    - Configuration using environment variables or command line arguments.
    - Debug mode to enable debug logging.
    - TLS enabled to secure the communication.
paths:
  /users:
    get:
      description: List all users
      operationId: 1213ffb2-b9f3-4134-923e-13bb777da62b
      parameters:
      - description: 'Comma-separated list of fields to sort by. Example: first_name
          ASC, created_at DESC'
        format: string
        in: query
        name: sort
        type: string
      - description: 'Filter field. Example: id=1 AND first_name=''John'''
        format: string
        in: query
        name: filter
        type: string
      - description: 'Fields to return. Example: id,first_name,last_name'
        format: string
        in: query
        name: fields
        type: string
      - description: Next cursor
        format: string
        in: query
        name: next_token
        type: string
      - description: Previous cursor
        format: string
        in: query
        name: prev_token
        type: string
      - description: Limit
        format: int
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListUsersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
      summary: List all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: |-
        Create a new user from scratch
        If the id is not provided, it will be generated automatically
      operationId: f71e14db-fc77-4fb3-a21d-292eade431df
      parameters:
      - description: CreateUserRequest
        format: json
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
      summary: Create a new user
      tags:
      - Users
  /users/{user_id}:
    delete:
      description: Delete a user
      operationId: 48e60e0a-ea1c-46d4-8729-c47dd82a4e93
      parameters:
      - description: The user ID in UUID format
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
      summary: Delete a user
      tags:
      - Users
    get:
      description: Get a user by ID
      operationId: b823ba3c-3b83-4eaa-bdf7-ce1b05237f23
      parameters:
      - description: The user ID in UUID format
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
      summary: Get a user by ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update a user
      operationId: 75165751-045b-465d-ba93-c88a27b6a42e
      parameters:
      - description: The user ID in UUID format
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      - description: User
        format: json
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
      summary: Update a user
      tags:
      - Users
  /users/health:
    get:
      description: |-
        This endpoint returns the health of the service
        validating the connection to the database
      operationId: 4c3b1fb4-1639-42ea-b6ca-8389b33ce5d4
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Health'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
      summary: Retrieve the health of the service
      tags:
      - Users
      - Health
  /version:
    get:
      description: Get the version of the service
      operationId: d85b4a3f-b032-4dd1-b3ab-bc9a00f95eb5
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Version'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/respond.HTTPMessage'
      summary: Get the version of the service
      tags:
      - Version
swagger: "2.0"
