definitions:
  handler.APIError:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
  model.Check:
    description: Check information.
    properties:
      data:
        additionalProperties: true
        description: Data is an optional field that can be used to provide additional
          information about the check.
        type: object
      kind:
        description: Kind is the kind of check.
        type: string
      name:
        description: Name is the name of the check.
        type: string
      status:
        description: Status is the status of the check.
        type: boolean
    type: object
  model.CreateUserRequest:
    description: Create user request.
    properties:
      email:
        description: Email is the email address of the user.
        type: string
      first_name:
        description: FirstName is the first name of the user.
        type: string
      id:
        description: ID is the unique identifier of the user.
        type: string
      last_name:
        description: LastName is the last name of the user.
        type: string
    type: object
  model.Health:
    description: Health information.
    properties:
      checks:
        description: Checks is a list of health checks.
        items:
          $ref: '#/definitions/model.Check'
        type: array
      status:
        description: Status is the status of the health check.
        type: boolean
    type: object
  model.ListUserResponse:
    properties:
      data:
        description: Items is a list of users.
        items:
          $ref: '#/definitions/model.User'
        type: array
      paginator:
        allOf:
        - $ref: '#/definitions/paginator.Paginator'
        description: Paginator is the paginator for the list of users.
    type: object
  model.UpdateUserRequest:
    description: Update user request.
    properties:
      email:
        description: Email is the email address of the user.
        type: string
      first_name:
        description: FirstName is the first name of the user.
        type: string
      last_name:
        description: LastName is the last name of the user.
        type: string
    type: object
  model.User:
    description: User information.
    properties:
      created_at:
        description: Email is the email address of the user.
        type: string
      email:
        description: Email is the email address of the user.
        type: string
      first_name:
        description: FirstName is the first name of the user.
        type: string
      id:
        description: ID is the unique identifier of the user.
        type: string
      last_name:
        description: LastName is the last name of the user.
        type: string
      updated_at:
        description: UpdatedAt is the time the user was last updated.
        type: string
    type: object
  paginator.Paginator:
    properties:
      limit:
        description: Limit is the maximum number of elements to return.
        type: integer
      next_page:
        description: NextPage the URL to the next page.
        type: string
      next_token:
        description: NextToken is the cursor token to the next page.
        type: string
      prev_page:
        description: PrevPage is the cursor token to the previous page.
        type: string
      prev_token:
        description: PrevToken is the cursor token to the previous page.
        type: string
      size:
        description: Size is the number of elements in the current page.
        type: integer
    type: object
  version.VersionInfo:
    properties:
      buildDate:
        type: string
      gitBranch:
        type: string
      gitCommit:
        type: string
      goVersion:
        type: string
      goVersionArch:
        type: string
      goVersionOS:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
  description: |-
    This is a service template for building RESTful APIs in Go.
    It uses a PostgreSQL database to store user information.
    The service provides:
    - CRUD operations for users.
    - Health and version endpoints.
    - Configuration using environment variables or command line arguments.
    - Debug mode to enable debug logging.
    - TLS enabled to secure the communication.
paths:
  /health:
    get:
      description: Get the health of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Health'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIError'
      summary: Get the health of the service
      tags:
      - health
  /healthz:
    get:
      description: Get the health of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Health'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIError'
      summary: Get the health of the service
      tags:
      - health
  /status:
    get:
      description: Get the health of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Health'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIError'
      summary: Get the health of the service
      tags:
      - health
  /users:
    get:
      description: List all users
      parameters:
      - description: 'Sort field. Example: first_name'
        in: query
        name: sort
        type: string
      - description: 'Filter field. Example: id=1 AND first_name=''John'''
        in: query
        name: filter
        type: string
      - description: 'Fields to return. Example: id,first_name,last_name'
        in: query
        name: fields
        type: string
      - description: Next cursor
        in: query
        name: next_token
        type: string
      - description: Previous cursor
        in: query
        name: prev_token
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ListUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIError'
      summary: List all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: |-
        Create a new user from scratch.
        If the id is not provided, it will be generated automatically.
      parameters:
      - description: CreateUserRequest
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIError'
      summary: Create a new user.
      tags:
      - users
  /users/{uid}:
    delete:
      description: Delete a user
      parameters:
      - description: The user ID in UUID format
        in: path
        name: uid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIError'
      summary: Delete a user
      tags:
      - users
    get:
      description: Get a user by ID
      parameters:
      - description: The user ID in UUID format
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIError'
      summary: Get a user by ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update a user
      parameters:
      - description: The user ID in UUID format
        in: path
        name: uid
        required: true
        type: string
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.APIError'
      summary: Update a user
      tags:
      - users
  /version:
    get:
      description: Get the version of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/version.VersionInfo'
      summary: Get the version of the service
      tags:
      - version
swagger: "2.0"
