name: Container Image

on:
  workflow_call:
    secrets:
      GH_PA_TOKEN:
        required: true
        description: 'GitHub token'
  workflow_dispatch:

env:
  MAKE_STOP_ON_ERRORS: true
  MAKE_DEBUG: true

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get -y install podman

      - name: Summary Information
        run: |
          echo "# Container Image Summary" > $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Tools and versions
        run: |
          echo "## Tools and versions" >> $GITHUB_STEP_SUMMARY

          ubuntu_version=$(cat /etc/os-release | grep "VERSION=" | awk -F= '{print $2}' | sed 's/"//g')
          echo "Ubuntu version: $ubuntu_version"
          echo "**Ubuntu Version:** $ubuntu_version" >> $GITHUB_STEP_SUMMARY

          bash_version=$(bash --version | head -n 1 | awk '{print $4}')
          echo "Bash version: $bash_version"
          echo "**Bash Version:** $bash_version" >> $GITHUB_STEP_SUMMARY

          git_version=$(git --version | awk '{print $3}')
          echo "Git version: $git_version"
          echo "**Git Version:** $git_version" >> $GITHUB_STEP_SUMMARY

          make_version=$(make --version | head -n 1)
          echo "Make version: $make_version"
          echo "**Make Version:** $make_version" >> $GITHUB_STEP_SUMMARY

          podman_version=$(podman --version | awk '{print $3}')
          echo "Podman version: $podman_version"
          echo "**Podman Version:** $podman_version" >> $GITHUB_STEP_SUMMARY

      - name: Download Distribution files
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist/

      - name: Make container-build
        run: |
          echo "## Make container-build" >> $GITHUB_STEP_SUMMARY
          GIT_VERSION=${{ github.ref_name }} make container-build | tee -a $GITHUB_STEP_SUMMARY

      - name: Make container-login
        run: |
          echo "## Make container-login" >> $GITHUB_STEP_SUMMARY
          GIT_VERSION=${{ github.ref_name }} REPOSITORY_REGISTRY_TOKEN=${{ secrets.GH_PA_TOKEN }} make container-login | tee -a $GITHUB_STEP_SUMMARY

      - name: Make container-publish
        run: |
          echo "## Make container-publish" >> $GITHUB_STEP_SUMMARY
          GIT_VERSION=${{ github.ref_name }} make container-publish | tee -a $GITHUB_STEP_SUMMARY