name: Main Branch

on:
  push:
    branches:
      - main

env:
  MAKE_STOP_ON_ERRORS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Summary Information
        run: |
          echo "# Main Branch Summary" > $GITHUB_STEP_SUMMARY
          echo "**Repository:** ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Author:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Tools and versions
        run: |
          echo "## Tools and versions" >> $GITHUB_STEP_SUMMARY

          ubuntu_version=$(lsb_release -a 2>&1 | grep "Description" | awk '{print $2, $3, $4}')
          echo "Ubuntu version: $ubuntu_version"
          echo "**Ubuntu Version:** $ubuntu_version" >> $GITHUB_STEP_SUMMARY

          bash_version=$(bash --version | head -n 1 | awk '{print $4}')
          echo "Bash version: $bash_version"
          echo "**Bash Version:** $bash_version" >> $GITHUB_STEP_SUMMARY

          git_version=$(git --version | awk '{print $3}')
          echo "Git version: $git_version"
          echo "**Git Version:** $git_version" >> $GITHUB_STEP_SUMMARY

          make_version=$(make --version | head -n 1 | awk '{print $3}')
          echo "Make version: $make_version"
          echo "**Make Version:** $make_version" >> $GITHUB_STEP_SUMMARY

          go_version=$(go version | awk '{print $3}')
          echo "Go version: $go_version"
          echo "**Go Version:** $go_version" >> $GITHUB_STEP_SUMMARY

      - name: make install-swag
        run: |
          echo "## Make install-swag" >> $GITHUB_STEP_SUMMARY
          make install-swag 2>&1 | tee -a $GITHUB_STEP_SUMMARY

      - name: Make tests
        run: |
          echo "## Make tests" >> $GITHUB_STEP_SUMMARY
          make test 2>&1 | tee -a $GITHUB_STEP_SUMMARY

      # - name: Make build-all
      #   run: |
      #     echo "## Make build" >> $GITHUB_STEP_SUMMARY
      #     make build-all 2>&1 | tee -a $GITHUB_STEP_SUMMARY
