name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Summary Information
        run: |
          SUMMARY="# Pull Request Summary"
          SUMMARY="$SUMMARY\n\n**Pull Request:** ${{ github.event.pull_request.title }}"
          SUMMARY="$SUMMARY\n**Author:** ${{ github.event.pull_request.user.login }}"
          SUMMARY="$SUMMARY\n**Branch:** ${{ github.event.pull_request.head.ref }}"
          SUMMARY="$SUMMARY\n**Base:** ${{ github.event.pull_request.base.ref }}"
          SUMMARY="$SUMMARY\n**Commits:** ${{ github.event.pull_request.commits }}"
          SUMMARY="$SUMMARY\n**Changed Files:** ${{ github.event.pull_request.changed_files }}"
          SUMMARY="$SUMMARY\n**Additions:** ${{ github.event.pull_request.additions }}"
          SUMMARY="$SUMMARY\n**Deletions:** ${{ github.event.pull_request.deletions }}"

          echo "$SUMMARY" >> "$GITHUB_STEP_SUMMARY"

      - name: Get Go version from package
        id: go_version
        run: |
          # Get Go version from go.mod
          version=$(grep 'go' go.mod | awk '{print $2}')
          echo "Go version: $version"

          # Write to output to be used in next steps
          echo "version=${version}" >> "$GITHUB_OUTPUT"

          # Write to Summary
          SUMMARY=$(cat "$GITHUB_STEP_SUMMARY")
          SUMMARY="$SUMMARY\n**Go Version:** $version"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go_version.outputs.version }}

      - name: Check Go version in the runner
        run: go version

      - name: Make tests
        run: make test

      - name: Make build
        run: make build
