name: Pull Request CI

on:
  pull_request:
    branches:
      - main

env:
  MAKE_STOP_ON_ERRORS: true # Stop on errors when running make

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Summary Information
        run: |
          echo "# Pull Request Summary" > $GITHUB_STEP_SUMMARY
          echo "**Pull Request:** ${{ github.event.pull_request.title }}" >> $GITHUB_STEP_SUMMARY
          echo "**Author:** ${{ github.event.pull_request.user.login }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.event.pull_request.head.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "**Base:** ${{ github.event.pull_request.base.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commits:** ${{ github.event.pull_request.commits }}" >> $GITHUB_STEP_SUMMARY
          echo "**Changed Files:** ${{ github.event.pull_request.changed_files }}" >> $GITHUB_STEP_SUMMARY
          echo "**Additions:** ${{ github.event.pull_request.additions }}" >> $GITHUB_STEP_SUMMARY
          echo "**Deletions:** ${{ github.event.pull_request.deletions }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Tools and versions
        run: |
          echo "## Tools and versions" >> $GITHUB_STEP_SUMMARY

          ubuntu_version=$(lsb_release -a 2>&1 | grep "Description" | awk '{print $2, $3, $4}')
          echo "Ubuntu version: $ubuntu_version"
          echo "**Ubuntu Version:** $ubuntu_version" >> $GITHUB_STEP_SUMMARY

          bash_version=$(bash --version | head -n 1 | awk '{print $4}')
          echo "Bash version: $bash_version"
          echo "**Bash Version:** $bash_version" >> $GITHUB_STEP_SUMMARY

          git_version=$(git --version | awk '{print $3}')
          echo "Git version: $git_version"
          echo "**Git Version:** $git_version" >> $GITHUB_STEP_SUMMARY

          make_version=$(make --version | head -n 1 | awk '{print $3}')
          echo "Make version: $make_version"
          echo "**Make Version:** $make_version" >> $GITHUB_STEP_SUMMARY

      - name: Get Go version from package
        id: go_version
        run: |
          # Get Go version from go.mod, the whitespace is important in the grep 'go ' command
          version=$(grep 'go ' go.mod | awk '{print $2}')
          echo "Go version: $version"

          # Write to output to be used in next steps
          echo "version=${version}" >> "$GITHUB_OUTPUT"

          # Write to Summary
          echo "**Go Version:** $version" >> $GITHUB_STEP_SUMMARY

      - name: Files changed
        run: |
          echo "## Files changed" >> $GITHUB_STEP_SUMMARY
          changed_files=$(git diff --name-only)
          echo "$changed_files"
          echo "**Changed Files:**" >> $GITHUB_STEP_SUMMARY

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^${{ steps.go_version.outputs.version }}"

      - name: Check Go version in the runner
        run: go version

      - name: Make tests
        run: |
          echo "## Make tests" >> $GITHUB_STEP_SUMMARY
          make test 2>&1 | tee -a $GITHUB_STEP_SUMMARY

      - name: Make build
        run: |
          echo "## Make build" >> $GITHUB_STEP_SUMMARY
          make build 2>&1 | tee -a $GITHUB_STEP_SUMMARY
