name: Release
on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]*

env:
  MAKE_STOP_ON_ERRORS: true

permissions:
  id-token: write
  security-events: write
  actions: write
  contents: write
  pull-requests: read
  packages: write

jobs:
  build:
    name: Build and release the application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Summary Information
        run: |
          echo "# Release Summary" > $GITHUB_STEP_SUMMARY
          echo "**Tag:** ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Tools and versions
        run: |
          echo "## Tools and versions" >> $GITHUB_STEP_SUMMARY

          ubuntu_version=$(lsb_release -a | grep "Description" | awk '{print $2, $3, $4}')
          echo "Ubuntu version: $ubuntu_version"
          echo "**Ubuntu Version:** $ubuntu_version" >> $GITHUB_STEP_SUMMARY

          bash_version=$(bash --version | head -n 1 | awk '{print $4}')
          echo "Bash version: $bash_version"
          echo "**Bash Version:** $bash_version" >> $GITHUB_STEP_SUMMARY

          git_version=$(git --version | awk '{print $3}')
          echo "Git version: $git_version"
          echo "**Git Version:** $git_version" >> $GITHUB_STEP_SUMMARY

          make_version=$(make --version | head -n 1 | awk '{print $3}')
          echo "Make version: $make_version"
          echo "**Make Version:** $make_version" >> $GITHUB_STEP_SUMMARY

          go_version=$(go version | awk '{print $3}')
          echo "Go version: $go_version"
          echo "**Go Version:** $go_version" >> $GITHUB_STEP_SUMMARY

      - name: make install-swag
        run: |
          echo "## Make install-swag" >> $GITHUB_STEP_SUMMARY
          make install-swag | tee -a $GITHUB_STEP_SUMMARY

      - name: Make tests
        run: |
          echo "## Make tests" >> $GITHUB_STEP_SUMMARY
          make test | tee -a $GITHUB_STEP_SUMMARY

      - name: Make build-dist
        run: |
          echo "## Make build-dist" >> $GITHUB_STEP_SUMMARY
          make build-dist | tee -a $GITHUB_STEP_SUMMARY

      - name: Make build-dist-zip
        run: |
          echo "## Make build-dist-zip" >> $GITHUB_STEP_SUMMARY
          make build-dist-zip | tee -a $GITHUB_STEP_SUMMARY

      - name: Create Release
        id: create-github-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          # body: |
          #   See the file: CHANGELOG.md
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          # files: |
          #   ./dist/assets/**

      - name: Upload Distribution files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/
          retention-days: 1

  containers:
    name: Create and publish container images
    needs: build
    uses: p2p-b2b/go-rest-api-service-template/.github/workflows/container-image.yaml@main
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}